# .codacy.yml
coverage:
  ignoreFiles:
    - '.devcontainer/**'
    - '.github/**'
    - '.husky/**'
    - 'assets/**'
    - 'tools/**'
    - '**/coverage/**'
    - '**/dist/**'
    - '**/*.config.ts'
    - '**/tests/**'
    - '**/*.json'
