name = "bunderlog-ingest"
main = "src/index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "bunderlog"
database_id = "97052d55-57e2-40f7-b099-25596b1a0802"

[vars]
MAX_BATCH_SIZE = "500"

# Secrets (set via wrangler secret put):
# LOG_TOKEN
